import '@mantine/core/styles.css';
import '@mantine/notifications/styles.css';
import type { Metadata } from "next";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import { theme } from "@/config/theme";
import { Providers } from './providers';
import { getLoggedUserCookie } from '@/services/auth-service';

// import { Inter } from "next/font/google";
// const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {

    let loggedUserData = getLoggedUserCookie();

    return (
        <html lang="en">
            <head>
                <ColorSchemeScript />
                <link rel="shortcut icon" href="/favicon.ico" />
                <meta
                    name="viewport"
                    content="minimum-scale=1, initial-scale=1, width=device-width, user-scalable=no"
                />
            </head>
            <body>
                <MantineProvider theme={theme} defaultColorScheme="auto">
                    <Providers loggedUserData={loggedUserData}>
                        {children}
                    </Providers>
                </MantineProvider>
            </body>
        </html>
    );
}
